spring.application.name=TrimurtiKiranaStores
spring.datasource.url=jdbc:mysql://localhost:3306/trimurtikiranastores_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update


spring.mail.host=smtp.gmail.com
spring.mail.username=storetrimurtikirana@gmail.com
spring.mail.password=
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

razorpay.api.key=
razorpay.api.secret=
server.servlet.session.persistent=false

# Razorpay Configuration
razorpay.key.id=
razorpay.key.secret=
